server:
  port: 9100
spring:
  datasource:
    url: jdbc:mysql://58.20.41.68:27018/seata_account?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: easyevent
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.251.53:8848
        namespace: 93346eb0-444c-47c0-8e12-ccba0070e06b
  application:
    name: seataAccount