server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        namespace: 93346eb0-444c-47c0-8e12-ccba0070e06b
        server-addr: 47.106.251.53:8848
    gateway:
      discovery:
        locator:
          # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，
        # 详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: user_route
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://user
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            - Path=/user/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedOrigins: '*'
            allowedMethods:
              - POST
                DELETE
                PUT
                OPTION
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
